### ISSUE TITLE
CS 1A EX 4 Values need to be entered into Next field

### ISSUE THREAD

**Issue by LaurieHeer** [MicrosoftLearning/MB-335-Dynamics-365-Supply-Chain-Management-Expert#8]
# Module: Module 2 Configure production prerequisites
#### Step: possibly alter steps 9 and 14

Description of issue
Possibly the entries into the scrap field should have been entered into the Next field
Repro steps:

9. In the Next field, enter 20.
14. In the Next field, enter 30.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! We are reviewing this and will provide an update once a resolution is in place, but it would be helpful if we had additional clarification regarding this issue that you are experiencing. Any additional details that you are able to provide is greatly appreciated! Please elaborate more on this request. 

ALH Hoster: 
Lab environment version: 
Is this your first encounter with this error? 
Which section of this exercise did you experience the issue? 
Additional Repro Steps:

**Comment by mstall1ngs** [comment]
The entries for Scrap Percentage in step 9 is for Assembly with a Link type of Soft. Step 14 is for Padding with a Scrap Percentage of 30 with a Link type of Hard. Please provide additional insight on your inquiry.

7. Select **New**.
8. In the **Operation** field, enter or select **Assembly**.
9. In the **Scrap Percentage** field, enter **20**.
10. In the **Link type** field, select **Soft**.
11. Select **New**.
12. In the **Oper. No.** field, enter **20**.
13. In the **Operation** field, enter or select **Padding**.
14. In the **Scrap percentage** field, enter **30**.
15. In the **Link type** field, select **Hard**.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! I did not run into any issues during replication with creating an operation, assigning relations nor creating a route. However, the instructions were updated to allocate the operation in sequential order by the 
**Next** operation that follows the current operation. If you selected **Route network** in the **Production control parameters** page, you can enter the next operation number manually. Otherwise, the next operation number is entered automatically, and you cannot enter any value in **Next** field. There can be only one last operation with a value of 0 (zero) which indicates that an operation in the route network is the last on the route. 

![image](https://github.com/user-attachments/assets/54288469-5fe8-4d82-8b3e-0c0d8991d768)
